-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 09:40:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laboratorio_objetos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboratorio_objetos` DEFAULT CHARACTER SET utf8 ;
USE `laboratorio_objetos` ;

-- -----------------------------------------------------
-- Table `laboratorio_objetos`.`Laboratorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio_objetos`.`Laboratorios` (
  `num_lab` INT NOT NULL AUTO_INCREMENT,
  `Metroscuadrados` DECIMAL(10,2) NULL, -- Cambié VARCHAR a DECIMAL para reflejar mejor un valor numérico
  `Num_mesa` INT NULL, -- Cambié VARCHAR a INT si se trata de un número
  PRIMARY KEY (`num_lab`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `laboratorio_objetos`.`OBJETOSLAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio_objetos`.`OBJETOSLAB` (
  `idObjeto` INT NOT NULL AUTO_INCREMENT,
  `PrecioObjeto` FLOAT NULL,
  `alto` DECIMAL(10,2) NULL,
  `ancho` DECIMAL(10,2) NULL,
  `Importancia` VARCHAR(45) NULL,
  `Laboratorios_num_lab` INT NOT NULL,
  PRIMARY KEY (`idObjeto`, `Laboratorios_num_lab`),
  CONSTRAINT `fk_OBJETOSLAB_Laboratorios`
    FOREIGN KEY (`Laboratorios_num_lab`)
    REFERENCES `laboratorio_objetos`.`Laboratorios` (`num_lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `laboratorio_objetos`.`Centros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio_objetos`.`Centros` (
  `idCentros` INT NOT NULL AUTO_INCREMENT,
  `NombreCentros` VARCHAR(45) NULL,
  `Numeros` VARCHAR(45) NULL,
  `CpPostal` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Laboratorios_num_lab` INT NOT NULL,
  PRIMARY KEY (`idCentros`, `Laboratorios_num_lab`),
  CONSTRAINT `fk_Centros_Laboratorios1`
    FOREIGN KEY (`Laboratorios_num_lab`)
    REFERENCES `laboratorio_objetos`.`Laboratorios` (`num_lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
drop database laboratorio_objetos;